---
# nakedBug blog configuration file
#
# Please change this config file before generating your asciidoc backend.
# There is no need to re-generate asciidoc backend if you change this config
# file, except for $blogtitle and $blogurl.

blogtitle: "Pingbo Wen's Blog"

# must add protocol before the url
blogroot: "http://pluvia.sinaapp.com"

# your posts location, each post should have a separated dir
# eg. 
# | --- {txtpath}
#       | --- catalog1
#             | --- firstpost
# 	          |     | --> firstpost.html
#             |     | --- css
#             |     | --- js
#             | --- secondpost
#                   | --> secondpost.html
#                   | --- ....
# related to blog root path
# the default posts location is article
# filename format: filename.MASK.adoc
# MASK:
#   0~7bit: catalog code <0 is default, range: 1~255>
#   8~11bit: highlight style code <0 is none, range: 1~15>
#   12~15bit: backend code <0 is standard asciidoctor template, range: 1~15>

# MASK definition:
mask_def:
    catalog:
        1: "android"
        2: "c-faq"
        3: "embedded_system"
        4: "linux_tips"
        5: "security"
# current asciidoctor support highlighters
    codestyle:
        1: "coderay"
        2: "highlightjs"
        3: "prettify"
        4: "pygments"
    backend:
        1: "simple"
        2: "small"
...
