= ADB常见错误分析
WEN Pingbo <wengpingbo@gmail.com>
Aug 13 2014

== ADB
ADB(Android Debug Bridge)是Google为了调试Android设备和Android模拟器实例而写的调试工具。整个ADB分为3个部分，ADB Server，ADB Client和ADB Daemon(adbd)。ADB Server是在主机上运行的一个进程，用来处理ADB Client和ADB Daemon之间的通信。平常所用的`adb kill-server`就是kill这个进程。ADB Client就是我们在终端里运行的程序，用于处理用户输入，并和ADB Server通信。通常ADB Client和ADB Server会编译到同一个可执行文件adb，所以在运行adb命令时，会主动检测是否有ADB Server这个进程，如果没有，就会默认后台运行ADB Server。ADB Daemon是一个运行在Android客户端的守护进程，用于和ADB Server进行通信，并给主机提供一系列的服务。

在我们平常的开发中，可能会碰到一些Android设备无法通过adb去连接。这里分析两种常见的连接错误。

== 设备找不到(device not found)
这种情况，一般现象是我们已经用USB把Android设备和主机连接在一起，但`adb devices`却无法正常识别该设备。但是通过`lsusb`命令却又能够看到该USB设备。

原因一般是ADB不识别该设备的VenderID。我们可以新建一个`$HOME/.android/adb_usb.ini`文件，把我们USB设备上的VenderID添加到该文件里，一个一行，然后运行`adb kill-server`把ADB Server干掉。之后我们就能够正常使用ADB连接到该Android设备。

关于这背后的具体细节，我们可以从ADB实现源码中找到。如果你现在手上有Android源码，可以在system/core/adb目录下找到ADB的实现代码。在ADB检测到一个USB设备时，会调用transport_usb.c:is_adb_interface函数。通过比对比对该设备的USB协议类型，VenderID等字段，来检测该USB设备是否支持ADB连接。而所用的VenderID都是在usb_vendors.c:usb_vendors_init函数里生成的。usb_venders_init函数首先会读取内置的VenderID，然后判断是否在指定的目录存在一个adb_usb.ini文件，如果存在，就把该文件里的VenderID也加进来。所以如果你的Android设备不在内置的VenderID之列，就只能在adb_usb.ini文件里手动添加了。

== 没权限(permission denied)/权限不足(insufficient permission)
这应该是比较常见的问题。这种问题，一般ADB可以发现该设备，但由于LINUX系统权限问题，无法在当前用户下打开该设备。于是就有了没权限的一说。这种情况其实跟ADB关系不大，解决思路一般是给设备节点文件分配相应的权限，我们可以通过设置udev的规则(/etc/udev/rules.d/)，让udev在发现该设备时，自动分配我们设置的权限。udev的规则语法如下：

[source, sh]
SUBSYSTEM=="usb", ATTR{idVendor}=="18d1", ATTR{idProduct}=="4e12", MODE="0600", OWNER="username"

我们也可以简单粗暴的用chmod命令临时改变/dev/bus/usb/下面的设备节点权限。

有的时候，你会发现按照上面做了，还是不行。请把udev服务重启，把ADB Server进程重启，把USB重插一遍，一般就能解决。如果还不能解决，我觉得你该检查你的USB线了。

this is a test
