= 2.14, 2.15-offsetof和struct成员异类访问
WEN Pingbo <wengpingbo AT gmail.com>
Jul 27 2013

今天在看c-faq的时候，碰到一个很奇怪的写法：

[source, c]
*(int *)((char *)structp + offsetf) = value;

其中offsetf是由offsetof宏计算出来的。这个表达式是用来不通过名字来引用结构体成员，而是通过偏移量来引用这个成员。感觉很有意思，那咱就深究一下吧！

首先，咱看一下offsetof这个ANSI C定义的宏，它是专门用来计算struct或者union类型成员的偏移量的。它的定义在stddef.h这个头文件中，用法很简单，给个例子就明白了：

[source, c]
----
struct test {
	char c;
	int i;
};
----

针对上面的结构体，offsetof(struct test, i)就会返回成员i在这个结构体中的相对偏移量。

用法清楚了，现在我对它的实现感兴趣！来看看它的源码！

在linux下面，如果你安装了kernel header的话，你可能会找到这个文件：/usr/include/linux/stddef.h。这个文件不是glibc的stddef.h，而是kernel用的头文件，如果你打开的话，发现这是一个空的头文件。其实用户态程序真真引用的stddef.h在你对应的编译器相关目录下面，由于我用的是gcc，所以要找的头文件在这：/usr/lib/gcc/x86_64-linux-gnu/4.7/include/stddef.h

打开这个头文件，定位到offsetof宏，发现它的定义是这样的：

[source, c]
----
/* Offset of member MEMBER in a struct of type TYPE. */
#define offsetof(TYPE, MEMBER) __builtin_offsetof (TYPE, MEMBER)
----

好吧，看来gcc并没有按照ANSI C来走，它这个地方做了一个跳转，网上的说法是为了兼容C++。先不管了，从标准stddef.h扒下来一份，发现有两种版本，最传统的版本是这样的：

[source, c]
#define offsetof(type,m) ((size_t)&(((type *)0)->m))

初看，你会觉得，额，有点复杂。其实把这个分解一下，还是可以理解的。这个表达式首先把一个null转换成一个type型的指针，然后用这个指针去引用成员m，然后取m的地址，并转换成大小。就相当于把一个结构体和0对齐，然后m的地址就是这个成员相对于结构体的相对偏移量了。

但是，这个并不是一个通用的实现方法。你可能会说，它引用了空指针，肯定运行不了。其实这并不算引用空指针问题，尽管表面上看上去是，因为这个偏移量是在编译时确定的，并不是在运行时。但是还是会有一些编译器拒绝接受这种写法，这要看具体的编译器的实现了。

既然那个版本不是通用的，那么修改一下：

[source, c]
#define offsetof(type,m) ( (size_t) (((char *)&(((type *)0)->m)) - (char *)((type *)0)) )

好吧，这个更复杂了。这个比上一个版本多做了两件事，一个是减去0的地址，这可以避免一些编译器的null并不是0的情况；另外一个是在做减法的时候，全部转成char *的类型，这就可以保证最后计算的结果是以字节为单位。

可能你会说，这个版本还是没有解决null指针引用的问题，那么就学学gcc把，直接用一个函数__builtin_offsetof，这个不但可以计算struct的偏移量，还能计算class的偏移量。

OK，清楚了offsetof的实现后，咱再回过头来看看那个struct成员的异类访问：

先定义一个结构体：

[source, c]
----
struct test {
	char c;
	int i;
	long l;
	double t;
};
----

再初始化一个实例：

[source, c]
struct test st;

假如我要把st中的t赋值为7.89，正常的写法，应该是这样的：

[source, c]
st.t=7.89;

那么，看一下另类写法：

[source, c]
*(double *)((char *)&st+offsetof(struct test, t))=7.89;

如果你真的看懂了offsetof的实现，那这个也就不是问题了。

其实在kernel开发中，还有一个类似的用法，那就是container_of,它是这样定义的：

[source, c]
----
#define container_of(ptr, type, member) ({ \
const typeof( ((type *)0)->member ) *__mptr = (ptr); \
(type *)( (char *)__mptr - offsetof(type,member) );})
----

上面那个用法，是通过struct的首地址，加上相对偏移量来确定某个成员的地址。而container_of是通过结构体内部的一个成员地址，减去它的偏移量，从而得到它的父结构体的首地址。就相当于一个指针往下移，一个往上移，原理是一样的！

附上我写这个文章的时候，写的实验代码，可以自己试一试：

[source, c]
.test.c
----
#include <stdio.h>

//#define offsetof(type,m) ((size_t)&(((type *)0)->m))
#define offsetof(type,m) ( (size_t) (((char *)&(((type *)0)->m)) - (char *)((type *)0)) )

struct test {
	char c;
	int i;
	long l;
	double t;
};

int main(int argc,char *argv[])
{
	struct test st;
	printf("t pre: %f\n",st.t);
	*(double *)((char *)&st+offsetof(struct test, t))=7.89;
	printf("i after:%f\n",st.t);
	return 0;
}
----