<div class="navbar navbar-inverse navbar-static-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="brand">WEN</a>
			<ul class="nav">
				<li><a class="active" href="#"><i class="icon-home icon-white"></i> Home</a></li>
				<li><a href="#"><i class="icon-th icon-white"></i> Project</a></li>
				<li><a href="#"><i class="icon-user icon-white"></i> About me</a></li>
				<li class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="icon-folder-open icon-white"></i> Catalog<b class="caret"></b></a>
				<ul class="dropdown-menu pull-right">
					<li><a tabindex="-1" href="#">Kernel Development</a></li>
					<li><a tabindex="-1" href="#">C Program</a></li>
					<li><a tabindex="-1" href="#">Scripts</a></li>
					<li><a tabindex="-1" href="#">Android</a></li>
				</ul>
				</li>
			</ul>
			<form class="navbar-search pull-right" action="">
                <input type="text" class="search-query span2" placeholder="Google Search">
            </form>
		</div>
	</div>
</div>
