<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="brand">WEN</a>
			<ul id="nav_item" class="nav">
				<li><a class="active" href="./"><i class="icon-home icon-white"></i> Home</a></li>
				<li><a href="#"><i class="icon-th icon-white"></i> Project</a></li>
				<li><a href="#"><i class="icon-user icon-white"></i> About me</a></li>
			</ul>
			<form class="navbar-search pull-right" action="">
                <input type="text" class="search-query span2" placeholder="Google Search">
            </form>
		</div>
	</div>
</div>
