<div class="navbar navbar-inverse navbar-fixed-top">
 <div class="navbar-inner">
  <div class="container">
   <a class="brand">
    WEN
   </a>
   <ul class="nav" id="nav_item">
    <li>
     <a class="active" href="http://202.201.0.164/blog">
      <i class="icon-home icon-white">
      </i>
      Home
     </a>
    </li>
    <li>
     <a href="#">
      <i class="icon-th icon-white">
      </i>
      Project
     </a>
    </li>
    <li>
     <a href="#">
      <i class="icon-user icon-white">
      </i>
      About me
     </a>
    </li>
   </ul>
   <form action="" class="navbar-search pull-right">
    <input class="search-query span2" placeholder="Google Search" type="text">
    </input>
   </form>
  </div>
 </div>
</div>
